# references:
asstantFieldsFilter: &assistantFieldsFilter
    allowed:
        - cin
        - fullname
        - birthdate
        - hasInsurance
        - address
        - phone
        - proffession

users:
    schema:
        timestamps: true
        fields:
            fullname:
                type: String
            username:
                type: String
                required: true
            role:
                type: String
                required: true
                enum: "'admin', 'dr', 'assistant'"
            password:
                type: String
                required: true
    permissions:
        default:
            enabled: true
        getAll:
            user:
                enabled: false

patients:
    schema:
        timestamps: true
        fields:
            fileNumber:
                type: String
                required: true
                auto:
                    pattern: increment
                    prefix: "P"
                    length: 6
            cin:
                type: String
            fullname:
                type: String
                required: true
            birthdate:
                type: Date
            hasInsurance:
                type: Boolean
                default: false
            address:
                type: String
            phone:
                type: String
            proffession:
                type: String
            atcdM:
                type: String
            atcdF:
                type: String
            atcdGo:
                type: String
            atcdCh:
                type: String
            atcdToxic:
                type: String
            weight:
                type: Number
            height:
                type: Number
            ta:
                type: String
            other:
                type: String
    permissions:
        default:
            enabled: true
        getAll:
            assistant:
                fieldsFilter: *assistantFieldsFilter
        getById:
            assistant:
                fieldsFilter: *assistantFieldsFilter
        create:
            assistant:
                fieldsFilter: *assistantFieldsFilter
        updateById:
            assistant:
                fieldsFilter: *assistantFieldsFilter
        search:
            assistant:
                fieldsFilter: *assistantFieldsFilter

consultations:
    schema:
        timestamps: true
        fields:
            patient:
                type: objectId
                required: true
            date:
                type: Date
                required: true
            reason:
                type: String
                required: true
            treatment:
                type: String
            echography:
                type: String
            lab:
                type: String
            followupDate:
                type: Date
            followupDesc:
                type: String
    permissions:
        default:
            enabled: true
        getAll:
            assistant:
                enabled: false
        getById:
            assistant:
                enabled: false
        create:
            assistant:
                enabled: false
        updateById:
            assistant:
                enabled: false
        deleteById:
            assistant:
                enabled: false

# End of config/smart-api.yaml
